name: "Run"

on:
  push:
    branches: ["main", "feature/run-on-github-actions"]

jobs:
  run:
    runs-on: "ubuntu-24.04"
    steps:
      - uses: "actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5" # v4.3.1
      - uses: "./.github/actions/get-elixir-version"
        id: "get-elixir-version"
      - uses: "erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93" # v1.24.0
        with:
          elixir-version: "${{ steps.get-elixir-version.outputs.version }}"
          otp-version: "27"
      - run: "elixir main.exs"
